-- 코드를 입력하세요
-- 그건 상관없음
-- 이렇게 쉼표별로 1개 세트
SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE,"%Y-%m-%d") START_DATE,  DATE_FORMAT(END_DATE,"%Y-%m-%d") END_DATE,
IF(DATEDIFF(END_DATE, START_DATE)+1 >= 30, '장기 대여', '단기 대여') RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE YEAR(START_DATE) = '2022' AND MONTH(START_DATE) = '09'
WHERE START_DATE LIKE '2022-09%'
ORDER BY HISTORY_ID DESC;
-- 단일행 함수였던거 같음 ㅇㅋㅇㅋbb
